name: bazaszachowa_flutter
description: "App for bazaszachowa.smallhost.pl"

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  chess: ^0.8.1
  chessground: ^7.1.3
  cupertino_icons: ^1.0.8
  dartchess: ^0.11.1
  flutter_svg: ^2.1.0
  font_awesome_flutter: ^10.8.0
  http: ^1.4.0
  url_launcher: ^6.3.1

  stockfish_chess_engine: ^0.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.svg
